// This variable `list` is automatically generated by the grunt generate-views-list task.
// Do not directly modify.

var list = [
  'views/blocks/footer',
  'views/blocks/header',
  'views/blocks/navigation',
  'views/pages/error',
  'views/pages/foo',
  'views/pages/fooList',
  'views/pages/home',
  'views/layout',
];
